### ISSUE TITLE
refactor: model

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/watch-tower#18]
Currently, watch tower depends on the model to do its tasks. 

Each version could introduce potentially breaking changes in the model, this of course would break the indexing. 
For this reason we kept the original model stable. 

However, it would be good to be able to evolve the model over time. 

Tasks:

- [x] Version model #21 
- [x] Do not use typechain generated structs

## Version model
This issue suggests using some versioning for the model, and some simple migration logics.

## Do not use IConditionalOrder.ConditionalOrderParamsStruct
IConditionalOrder.ConditionalOrderParamsStruct has a weird definition:

```ts
export type ConditionalOrderParamsStruct = {
    handler: PromiseOrValue<string>;
    salt: PromiseOrValue<BytesLike>;
    staticInput: PromiseOrValue<BytesLike>;
  };
```

Actually, this is not what ends up being persisted. See the hack: https://github.com/cowprotocol/tenderly-watch-tower/blob/88ab5365f303a0f316b70eaea98a1604767ba45a/actions/checkForAndPlaceOrder.ts#L201

```ts
const [handler, salt, staticInput] = conditionalOrder.params as any as [
      string,
      string,
      string
    ];
```

## 
https://github.com/cowprotocol/tenderly-watch-tower/blob/88ab5365f303a0f316b70eaea98a1604767ba45a/actions/checkForAndPlaceOrder.ts#L199

**Comment by mfw78** [comment]
@anxolin Given #21 introduces versioning, I'll close this issue. If it hasn't been addressed, please re-open 🙏

**Comment by mfw78** [comment]
Per #84 this now closes out the struct use.
