### ISSUE TITLE
feat: single-chain mode

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/watch-tower#71]
### Problem
The current default mode for running the watch-tower is only multi-chain. This is a requirement for self-hosted (eg. dappnode), however there's minimal blast radius protection (one chain may affect another's watch-tower).

### Suggested solution
Implement a single-chain mode.

### Alternatives considered
Build blast radius protection into the current `run` mode of the watch-tower. This is likely an over-engineered solution that can be mitigated better by strict division between chain micro-services.

### Acceptance criteria

- [ ] `run` command moved to `run-multi`.
- [ ] `run` command implements a single chain's watch-tower.
- [ ] Command line configuration options for single-run are backwards compatible.

**Comment by Kaivanshah1** [comment]
can you provide any video or screenshot to understand better?

**Comment by mfw78** [comment]
> can you provide any video or screenshot to understand better?

Please kindly refer to the code base and the issue descriptor. There is no video or screenshot as this repo is a service, not front-end facing.
