### ISSUE TITLE
chore: Setup alerts

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/watch-tower#81]
### Background
Research on best way to create alerts, define channels, and process to review issues. 

Probably we will use Grafana/Prometheus for this. But validate with backend

**Comment by anxolin** [comment]
Well, we set it up, but i think we will need to iterate now. I can make a new issue or re-open this one. Its too noisy

**Comment by mfw78** [comment]
@anxolin Can this be closed with the grafana queries being done?
