### ISSUE TITLE
chore: Address comments in consolidated PRs

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/watch-tower#89]
### Background
We are deploying watch tower to PROD, and we need some of the changes in the open PRs. This is why I will consolidate all those open PRs and close version.

Some PRs have follow ups, so this issue is just a reminder to handle the comments:

Merged this PR but might have some comments:
- [x] @ahhda  https://github.com/cowprotocol/watch-tower/pull/87
- [x] @anxolin  https://github.com/cowprotocol/watch-tower/pull/84
- [x] @anxolin https://github.com/cowprotocol/watch-tower/pull/86
- [x] @mfw78 https://github.com/cowprotocol/watch-tower/pull/74
- [x] @mfw78 https://github.com/cowprotocol/watch-tower/pull/75 (was in draft when i merged)
- [x] @anxolin https://github.com/cowprotocol/watch-tower/pull/90

**Comment by mfw78** [comment]
Tasks for this have active PRs. Closing issue.
