### ISSUE TITLE
chore: Store the context

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/watch-tower#9]
When we index a new order, there might be already some context information that we want to include.

Instead of fetching the context over and over for following checks, we can just store it when we add an order.

For TWAP it means, we store the t0

**Comment by mfw78** [comment]
I'm not sure that we should be doing this in the watch tower. I think the watch tower would be better equipped to pass a `provider` to the `poll` method, at which time this can be used with the stored `params` (so, in the case of `TWAP`, `t0 = 0`). Then with the `poll` method being passed a provider, the concrete conditional order knows that it needs to fetch the `context`.

Balancing storing the context vs retrieving on poll:

**Pros**: 
- Reduce footprint where stored data may drift from on-chain state (eg. someone recreates the exact same TWAP, this would result in the stored context potentially being out of sync, but could be handled by storing the context again on the `addContract`.
- Re-org data consistency becomes a reducing consideration.
- Reduce storage size (32 bytes per order + `JSON` serialization)

**Cons**:
- An additional `RPC` call on each `poll`, however, this can be overcome by using a `multicall` and bundling the `context` fetching and the `getTradeableOrderWithSignature` together?

Are there any specific reasons why we would need the context, or things missed above?

**Comment by mfw78** [comment]
I'm going to close this as `wont-fix`.
